### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thewh1teagle** [thewh1teagle/tauric#2]
## Todo; sorted by priority

Goal: No need for Cargo / Rust!

- [x] Dynamic identifier from Python https://github.com/tauri-apps/tauri/discussions/5964#discussioncomment-4591262
- [x] Dynamic app name from Python
- [x] Custom IPC protocol crash on macOS when reading a file. https://github.com/tauri-apps/wry/issues/1189
- [x] Load local files using custom protocl **ONLY** after bindings enabled it.
- [x] PyPI package https://github.com/astral-sh/uv
- [x] CI to build cross platform packages with static / dynamic lib https://github.com/thewh1teagle/aec-rs
- [ ] Dynamic icon from Python https://github.com/tauri-apps/tauri/discussions/6527#discussioncomment-5394327  https://github.com/tauri-apps/tauri/issues/2358#issuecomment-2529426695 https://stackoverflow.com/questions/18314659/setting-program-icon-without-resources-using-the-win32-api https://developer.apple.com/documentation/appkit/nsapplication/applicationiconimage
- [ ] Dynamic capabilities
- [ ] Bundle with PyInstaller into single executable https://github.com/crabnebula-dev/cargo-packager
- [ ] Memory management cleanup and null safety 
- [ ] Dev server with hot reload
- [ ] Bundle including frontend with Go into a single executable https://github.com/crabnebula-dev/cargo-packager
- [ ] Better IPC https://github.com/tauri-apps/tauri/discussions/5597#discussion-4552722
- [ ] Go package https://github.com/ebitengine/purego
- [ ] NPM package https://github.com/zhangyuang/node-ffi-rs
- [ ] Tauri plugins from shared libraries
- [ ] API function to enable hot reload by register a folder to watch. Rust will iterate windows and reload them. https://github.com/notify-rs/notify
